drop table if exists terms;
drop table if exists contributors;
drop table if exists admins;

CREATE TABLE terms (
  id       SERIAL PRIMARY KEY,
  term     VARCHAR(30) NOT NULL,
  definitions TEXT NOT NULL,
  links  TEXT[],
  admin_id INT,
  programming_language VARCHAR(20),
  contributor_id INT,
  creation_date DATE DEFAULT NOW()zzzz,
  last_edit_date DATE
);

CREATE TABLE contributors (
  id       SERIAL PRIMARY KEY,
  contributor_name     VARCHAR(120) NOT NULL,
  region    VARCHAR(20) NOT NULL,
  email VARCHAR(30)
);

CREATE TABLE admins (
  id            SERIAL PRIMARY KEY,
  admin_name   VARCHAR(100) NOT NULL,
  email      VARCHAR(100),
  admin_password  VARCHAR(30)
);

INSERT INTO admins (admin_name, email, admin_password) VALUES ('Tina', 'Tina@email', 'Funny');
INSERT INTO admins (admin_name, email, admin_password) VALUES ('Frank', 'F@google', 'Star');
INSERT INTO admins (admin_name, email, admin_password) VALUES ('Claire', 'Claire@yahoo.com', 'Time');

INSERT INTO terms (term, definitions, links, admin_id, programming_language, contributor_id) VALUES ('Class','HTML elements can have one or more classes, separated by spaces. You can style elements using CSS by selecting them with their classes.', '{"https://www.youtube.com/watch?v=wXUhTZpF_HQ", "https://www.youtube.com/watch?v=UB1O30fR-EE", "https://www.w3schools.com/html/html_classes.asp", "https://developer.mozilla.org/en-US/docs/Web/HTML/Global_attributes/class"}', 1,'HTML', 2);
INSERT INTO terms (term, definitions, links, admin_id, programming_language, contributor_id) VALUES ('Body','The body is the container for all of a page’s content. Comes after the <head> tag, within the overall <html> tag.', '{"https://www.youtube.com/watch?v=RgwEVLoExGQ", "https://www.youtube.com/watch?v=mNRzWMH5xK0", "https://www.w3schools.com/tags/tag_body.asp", "https://developer.mozilla.org/en-US/docs/Web/HTML/Element/body"}', 2,'HTML', 1);
INSERT INTO terms (term, definitions, links, admin_id, programming_language, contributor_id) VALUES ('Id','An HTML element can have an id attribute to identify it. id elements should always be unique to that single element, and each element should never have more than one id.', '{"https://www.youtube.com/watch?v=wXUhTZpF_HQ", "https://www.youtube.com/watch?v=-voQMXA_H6s", "https://www.w3schools.com/html/html_id.asp", "https://developer.mozilla.org/en-US/docs/Web/HTML/Global_attributes/id"}',3,'HTML', 1);
INSERT INTO terms (term, definitions, links, admin_id, programming_language, contributor_id) VALUES ('Header','Heading elements like <h1>, <h2>, <h3>, … allow you to use six levels of document headings, ranging from largest to smallest, breaking up the document into logical sections. For example, the word ‘Headings’ above is wrapped in a <h2> tag.', '{"https://www.youtube.com/watch?v=H519o8BvpQA", "https://www.youtube.com/watch?v=Pq9DkCt4fqI", "https://www.w3schools.com/html/html_headings.asp", "https://developer.mozilla.org/en-US/docs/Web/HTML/Element/Heading_Elements"}',2,'HTML', 3);
INSERT INTO terms (term, definitions, links, admin_id, programming_language, contributor_id) VALUES ('href','Links tell the browser where to go using an href attribute, which stores a URL.', '{"https://www.youtube.com/watch?v=tK4nF_TPQyo", "https://www.youtube.com/watch?v=GxwHXxumdQk", "https://www.w3schools.com/tags/att_a_href.asp", "https://developer.mozilla.org/en-US/docs/Web/HTML/Element/a"}',1,'HTML',2);
INSERT INTO terms (term, definitions, links, admin_id, programming_language, contributor_id) VALUES ('align-items','The CSS align-items property sets the align-self value on all direct children as a group. In Flexbox, it controls the alignment of items on the Cross Axis. In Grid Layout, it controls the alignment of items on the Block Axis within their grid area.', '{"https://www.youtube.com/watch?v=BUNsmd17YB4", "https://www.youtube.com/watch?v=XIJZjhqs7m0", "https://www.w3schools.com/cssref/css3_pr_align-items.asp", "https://developer.mozilla.org/en-US/docs/Web/CSS/align-items"}',2,'CSS',1);
INSERT INTO terms (term, definitions, links, admin_id, programming_language, contributor_id) VALUES ('flex','The flex CSS shorthand property sets how a flex item will grow or shrink to fit the space available in its flex container.', '{"https://www.youtube.com/watch?v=fYq5PXgSsbE", "https://www.youtube.com/watch?v=fqNPSSoMO9Y", "https://www.w3schools.com/cssref/css3_pr_flex.asp", "https://developer.mozilla.org/en-US/docs/Web/CSS/flex"}',2,'CSS',2);
INSERT INTO terms (term, definitions, links, admin_id, programming_language, contributor_id) VALUES ('Grid','To specify the number of columns of the grid and the widths of each column, the CSS property grid-template-columns is used on the grid container. The number of width values determines the number of columns and each width value can be either in pixels(px) or percentages(%).', '{"https://www.youtube.com/watch?v=9zBsdzdE4sM", "https://www.youtube.com/watch?v=EFafSYg-PkI", "https://www.w3schools.com/cssref/pr_grid.asp", "https://developer.mozilla.org/en-US/docs/Glossary/Grid"}',3,'CSS',3);
INSERT INTO terms (term, definitions, links, admin_id, programming_language, contributor_id) VALUES ('Margin','The margin property sets the margins for an element, and is a shorthand property for the following properties:margin-top,margin-right,margin-bottom,margin-left.', '{"https://www.youtube.com/watch?v=EhbZGV2dqZ4", "https://www.youtube.com/watch?v=Azfj1efPAH0", "https://www.w3schools.com/cssref/pr_margin.asp", "https://developer.mozilla.org/en-US/docs/Web/CSS/margin"}',1,'CSS',2);
INSERT INTO terms (term, definitions, links, admin_id, programming_language, contributor_id) VALUES ('text-align','The text-align property specifies the horizontal alignment of text in an element.', '{"https://www.youtube.com/watch?v=sLAunIX5RXw", "https://www.youtube.com/watch?v=4Y1XlQ7bsCI", "https://www.w3schools.com/cssref/pr_text_text-align.asp", "https://developer.mozilla.org/en-US/docs/Web/CSS/text-align"}',2,'CSS',1);
INSERT INTO terms (term, definitions, links, admin_id, programming_language, contributor_id) VALUES ('Variable','JavaScript variables are containers for storing data values.', '{"https://www.youtube.com/watch?v=edlFjlzxkSI", "https://www.youtube.com/watch?v=u0Mq3FzpsmI", "https://www.w3schools.com/js/js_variables.asp", "https://developer.mozilla.org/en-US/docs/Glossary/Variable"}',1,'Javascript',2);
INSERT INTO terms (term, definitions, links, admin_id, programming_language, contributor_id) VALUES ('Loop','Loops can execute a block of code a number of times.', '{"https://www.youtube.com/watch?v=s9wW2PpJsmQ", "https://www.youtube.com/watch?v=24Wpg6njlYI", "https://www.w3schools.com/js/js_loop_for.asp", "https://developer.mozilla.org/en-US/docs/Learn/JavaScript/Building_blocks/Looping_code"}',3,'Javascript',1);
INSERT INTO terms (term, definitions, links, admin_id, programming_language, contributor_id) VALUES ('Boolean','A JavaScript Boolean represents one of two values: true or false.', '{"https://www.youtube.com/watch?v=yVJR6QyF2uk", "https://www.youtube.com/watch?v=Rk-_syQluvc", "https://www.w3schools.com/js/js_booleans.asp", "https://developer.mozilla.org/en-US/docs/Glossary/Boolean"}', 1,'Javascript', 2);
INSERT INTO terms (term, definitions, links, admin_id, programming_language, contributor_id) VALUES ('Array','An array is a special variable, which can hold more than one value at a time.','{"https://www.youtube.com/watch?v=R8rmfD9Y5-c", "https://www.youtube.com/watch?v=orAS-MBh5f4", "https://www.w3schools.com/js/js_arrays.asp", "https://developer.mozilla.org/en-US/docs/Glossary/array"}',1, 'Javascript',1);
INSERT INTO terms (term, definitions, links, admin_id, programming_language, contributor_id) VALUES ('Object','The Object class represents one of JavaScripts data types. It is used to store various keyed collections and more complex entities.','{"https://www.youtube.com/watch?v=PFmuCDHHpwk", "https://www.youtube.com/watch?v=X0ipw1k7ygU", "https://www.w3schools.com/js/js_objects.asp", "https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Object"}',2, 'Javascript',3);


INSERT INTO terms (term, definitions, links, admin_id, programming_language, contributor_id) VALUES ('SELECT Statement','The SELECT statement is used to select data from a database. The data returned is stored in a result table, called the result-set.', '{"https://youtu.be/YufocuHbYZo", "https://youtu.be/gbHXhXmACgI", "https://www.w3schools.com/sql/sql_select.asp", "https://www.codecademy.com/courses/learn-sql/lessons/manipulation/exercises/select"}', 2,'SQL', 1);
INSERT INTO terms (term, definitions, links, admin_id, programming_language, contributor_id) VALUES ('SELECT DISTINCT Statement','The SELECT DISTINCT statement is used to return only distinct (different) values. Inside a table, a column often contains many duplicate values; and sometimes you only want to list the different (distinct) values.', '{"https://youtu.be/dGo9T1pQzPk", "https://youtu.be/zp0_edjxuyU", "https://www.w3schools.com/sql/sql_distinct.asp", "https://www.codecademy.com/courses/learn-sql/lessons/manipulation/exercises/select"}', 2,'SQL', 1);
INSERT INTO terms (term, definitions, links, admin_id, programming_language, contributor_id) VALUES ('WHERE Clause','The WHERE clause is used to filter records. The WHERE clause is used to extract only those records that fulfill a specified condition.', '{"https://youtu.be/vxlD94G0Geo", "https://youtu.be/JeZCabShIFk", "https://www.w3schools.com/sql/sql_where.asp", "https://www.codecademy.com/articles/sql-commands"}', 2,'SQL', 1);
INSERT INTO terms (term, definitions, links, admin_id, programming_language, contributor_id) VALUES ('AND, OR and NOT Operators','The WHERE clause can be combined with AND, OR, and NOT operators. The AND and OR operators are used to filter records based on more than one condition: The AND operator displays a record if all the conditions separated by AND are TRUE. The OR operator displays a record if any of the conditions separated by OR is TRUE. The NOT operator displays a record if the condition(s) is NOT TRUE.', '{"https://youtu.be/vxlD94G0Geo", "https://youtu.be/JeZCabShIFk", "https://www.w3schools.com/sql/sql_and_or.asp", "https://www.codecademy.com/articles/sql-commands"}', 2,'SQL', 1);
INSERT INTO terms (term, definitions, links, admin_id, programming_language, contributor_id) VALUES ('ORDER BY Keyword','The ORDER BY keyword is used to sort the result-set in ascending or descending order.The ORDER BY keyword sorts the records in ascending order by default. To sort the records in descending order, use the DESC keyword.', '{"https://youtu.be/6Rrau_fr7p0", "https://youtu.be/6YGvqrwQ9d4", "https://www.w3schools.com/sql/sql_orderby.asp", "https://www.codecademy.com/articles/sql-commands"}', 2,'SQL', 1);
INSERT INTO terms (term, definitions, links, admin_id, programming_language, contributor_id) VALUES ('INSERT INTO Statement','The INSERT INTO statement is used to insert new records in a table.', '{"https://youtu.be/VkabxQgtGsA", "https://youtu.be/Tet3Z7Yb2gg", "https://www.w3schools.com/sql/sql_insert.asp", "https://www.codecademy.com/articles/sql-commands"}', 2,'SQL', 1);
INSERT INTO terms (term, definitions, links, admin_id, programming_language, contributor_id) VALUES ('NULL Value','A field with a NULL value is a field with no value. If a field in a table is optional, it is possible to insert a new record or update a record without adding a value to this field. Then, the field will be saved with a NULL value.', '{"https://youtu.be/6Rrau_fr7p0", "https://youtu.be/6YGvqrwQ9d4", "https://www.w3schools.com/sql/sql_orderby.asp", "https://www.codecademy.com/articles/sql-commands"}', 2,'SQL', 1);
INSERT INTO terms (term, definitions, links, admin_id, programming_language, contributor_id) VALUES ('UPDATE Statement','The UPDATE statement is used to modify the existing records in a table.', '{"https://youtu.be/6Rrau_fr7p0", "https://youtu.be/6YGvqrwQ9d4", "https://www.w3schools.com/sql/sql_orderby.asp", "https://www.codecademy.com/articles/sql-commands"}', 2,'SQL', 1);
INSERT INTO terms (term, definitions, links, admin_id, programming_language, contributor_id) VALUES ('DELETE Statement','The DELETE statement is used to delete existing records in a table.', '{"https://youtu.be/6Rrau_fr7p0", "https://youtu.be/6YGvqrwQ9d4", "https://www.w3schools.com/sql/sql_orderby.asp", "https://www.codecademy.com/articles/sql-commands"}', 2,'SQL', 1);
INSERT INTO terms (term, definitions, links, admin_id, programming_language, contributor_id) VALUES ('SELECT TOP Clause','The SELECT TOP clause is used to specify the number of records to return. The SELECT TOP clause is useful on large tables with thousands of records. Returning a large number of records can impact performance.', '{"https://youtu.be/6Rrau_fr7p0", "https://youtu.be/6YGvqrwQ9d4", "https://www.w3schools.com/sql/sql_orderby.asp", "https://www.codecademy.com/articles/sql-commands"}', 2,'SQL', 1);
INSERT INTO terms (term, definitions, links, admin_id, programming_language, contributor_id) VALUES ('MIN and MAX Functions','The MIN() function returns the smallest value of the selected column. The MAX() function returns the largest value of the selected column.', '{"https://youtu.be/6Rrau_fr7p0", "https://youtu.be/6YGvqrwQ9d4", "https://www.w3schools.com/sql/sql_orderby.asp", "https://www.codecademy.com/articles/sql-commands"}', 2,'SQL', 1);
INSERT INTO terms (term, definitions, links, admin_id, programming_language, contributor_id) VALUES ('COUNT AVG and SUM Functions','The COUNT() function returns the number of rows that matches a specified criterion. The AVG() function returns the average value of a numeric column. The SUM() function returns the total sum of a numeric column.', '{"https://youtu.be/6Rrau_fr7p0", "https://youtu.be/6YGvqrwQ9d4", "https://www.w3schools.com/sql/sql_orderby.asp", "https://www.codecademy.com/articles/sql-commands"}', 2,'SQL', 1);
INSERT INTO terms (term, definitions, links, admin_id, programming_language, contributor_id) VALUES ('LIKE Operator','The LIKE operator is used in a WHERE clause to search for a specified pattern in a column. There are two wildcards often used in conjunction with the LIKE operator: % - The percent sign represents zero, one, or multiple characters _ - The underscore represents a single character', '{"https://youtu.be/6Rrau_fr7p0", "https://youtu.be/6YGvqrwQ9d4", "https://www.w3schools.com/sql/sql_orderby.asp", "https://www.codecademy.com/articles/sql-commands"}', 2,'SQL', 1);
INSERT INTO terms (term, definitions, links, admin_id, programming_language, contributor_id) VALUES ('Wildcard Characters','A wildcard character is used to substitute one or more characters in a string. Wildcard characters are used with the SQL LIKE operator. The LIKE operator is used in a WHERE clause to search for a specified pattern in a column.', '{"https://youtu.be/6Rrau_fr7p0", "https://youtu.be/6YGvqrwQ9d4", "https://www.w3schools.com/sql/sql_orderby.asp", "https://www.codecademy.com/articles/sql-commands"}', 2,'SQL', 1);
INSERT INTO terms (term, definitions, links, admin_id, programming_language, contributor_id) VALUES ('IN Operator','The IN operator allows you to specify multiple values in a WHERE clause. The IN operator is a shorthand for multiple OR conditions.', '{"https://youtu.be/6Rrau_fr7p0", "https://youtu.be/6YGvqrwQ9d4", "https://www.w3schools.com/sql/sql_orderby.asp", "https://www.codecademy.com/articles/sql-commands"}', 2,'SQL', 1);
INSERT INTO terms (term, definitions, links, admin_id, programming_language, contributor_id) VALUES ('BETWEEN Operator','The BETWEEN operator selects values within a given range. The values can be numbers, text, or dates. The BETWEEN operator is inclusive: begin and end values are included.', '{"https://youtu.be/6Rrau_fr7p0", "https://youtu.be/6YGvqrwQ9d4", "https://www.w3schools.com/sql/sql_orderby.asp", "https://www.codecademy.com/articles/sql-commands"}', 2,'SQL', 1);
INSERT INTO terms (term, definitions, links, admin_id, programming_language, contributor_id) VALUES ('Aliases','SQL aliases are used to give a table, or a column in a table, a temporary name. Aliases are often used to make column names more readable. An alias only exists for the duration of the query.', '{"https://youtu.be/6Rrau_fr7p0", "https://youtu.be/6YGvqrwQ9d4", "https://www.w3schools.com/sql/sql_orderby.asp", "https://www.codecademy.com/articles/sql-commands"}', 2,'SQL', 1);
INSERT INTO terms (term, definitions, links, admin_id, programming_language, contributor_id) VALUES ('JOIN','A JOIN clause is used to combine rows from two or more tables, based on a related column between them.', '{"https://youtu.be/6Rrau_fr7p0", "https://youtu.be/6YGvqrwQ9d4", "https://www.w3schools.com/sql/sql_orderby.asp", "https://www.codecademy.com/articles/sql-commands"}', 2,'SQL', 1);
INSERT INTO terms (term, definitions, links, admin_id, programming_language, contributor_id) VALUES ('INNER JOIN Keyword','The INNER JOIN keyword selects records that have matching values in both tables.', '{"https://youtu.be/wz6XnW9nk4w", "https://youtu.be/2HVMiPPuPIM", "https://www.w3schools.com/sql/sql_join_inner.asp", "https://www.codecademy.com/articles/sql-commands"}', 2,'SQL', 1);
INSERT INTO terms (term, definitions, links, admin_id, programming_language, contributor_id) VALUES ('LEFT JOIN Keyword','The LEFT JOIN keyword returns all records from the left table (table1), and the matched records from the right table (table2). The result is NULL from the right side, if there is no match.', '{"https://youtu.be/2HVMiPPuPIM", "https://youtu.be/ajPjRoLG_3A", "https://www.w3schools.com/sql/sql_join_left.asp", "https://www.codecademy.com/articles/sql-commands"}', 2,'SQL', 1);
INSERT INTO terms (term, definitions, links, admin_id, programming_language, contributor_id) VALUES ('RIGHT JOIN Keyword','The RIGHT JOIN keyword returns all records from the right table (table2), and the matched records from the left table (table1). The result is NULL from the left side, when there is no match.', '{"https://youtu.be/2HVMiPPuPIM", "https://youtu.be/ajPjRoLG_3A", "https://www.w3schools.com/sql/sql_join_right.asp", "https://www.codecademy.com/articles/sql-commands"}', 2,'SQL', 1);
INSERT INTO terms (term, definitions, links, admin_id, programming_language, contributor_id) VALUES ('FULL OUTER JOIN Keyword','The FULL OUTER JOIN keyword returns all records when there is a match in left (table1) or right (table2) table records. Note: FULL OUTER JOIN can potentially return very large result-sets!', '{"https://youtu.be/2HVMiPPuPIM", "https://youtu.be/5tCOkFAvWkw", "https://www.w3schools.com/sql/sql_join_full.asp", "https://www.codecademy.com/articles/sql-commands"}', 2,'SQL', 1);
INSERT INTO terms (term, definitions, links, admin_id, programming_language, contributor_id) VALUES ('Self JOIN','A self JOIN is a regular join, but the table is joined with itself.', '{"https://youtu.be/G4vO83UUzek", "https://youtu.be/KHiQr3MG_8E", "https://www.w3schools.com/sql/sql_join_self.asp", "https://www.codecademy.com/articles/sql-commands"}', 2,'SQL', 1);

INSERT INTO contributors (contributor_name, region, email) VALUES ('Paul', 'West Midlands', 'Paul@com');
INSERT INTO contributors (contributor_name, region, email) VALUES ('Sunayna', 'West Midlans', 'Sunayna@com');
INSERT INTO contributors (contributor_name, region, email) VALUES ('Kevin', 'London', 'Kevin@com');



